pilot:
  autoscaleMin: 2
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: "istio"
            operator: In
            values:
            - pilot
        topologyKey: "kubernetes.io/hostname"
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 1
      preference:
        matchExpressions:
        # Try to put pods on the non-spot (default) pool node, if it exists
        - key: "cloud.google.com/gke-nodepool"
          operator: In
          values:
          - "default-pool"